apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 10 
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: iminsik 
        image: iminsik/node-web-app 
        ports:
        - name: nodejs-port
          containerPort: 8080 
        livenessProbe:
          httpGet:
            path: /
            port: nodejs-port
          initialDelaySeconds: 10
          timeoutSeconds: 20
